name: CI
on:
  push:
  release:
    types: [released]

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: tomeichlersmith/ldmx-ci-data-testbench
        path: ci-data
    - run: find . ! -path '*.git/**' -type f -print -exec cat {} ';'
  write:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: tomeichlersmith/ldmx-ci-data-testbench
        path: ci-data
        token: ${{ secrets.PAT }}
    - run: find . ! -path '*.git/**' -type f -print -exec cat {} ';'
    - run: |
        git describe --tags
        echo ${GITHUB_SHA}
        echo ${GITHUB_REF}
        echo ${GITHUB_REF##refs/tags/}
      shell: bash
    - run: |
          git config --global user.name ci-data-update-bot
          git config --global user.email ci-data-update-bot@users.noreply.github.com
          cd ci-data
          git add .
          git commit --amend -m "ci data update" || exit 0
          git push -fu origin main
